cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='detail'),
    path('add/<int:product_id>/', views.cart_add, name='add'),
    path('remove/<int:product_id>/', views.cart_remove, name='remove'),
    path('clear/', views.cart_clear, name='clear'), 
]

controller/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', include('menu.urls', namespace="menu")),
    path('user/', include('user.urls', namespace="user")),
    path('cart/', include('cart.urls', namespace="cart")),
    path('', include('shop.urls', namespace="shop")),
]

if settings.DEBUG or settings.TESTING_MODE:
    import debug_toolbar
    urlpatterns += [url('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'

urlpatterns = [
    path('', views.index, name="index"),
    path('add/', views.add_to_cart, name="add"),
    path('order/', views.create_order, name="order"),
    path('order-created/', views.order_created, name="order_created"),
]

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 6)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label='Quantity')
    override = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.views.decorators.http import require_POST

from .cart import Cart
from .forms import CartAddProductForm

from user.forms import AddressSelectForm
from menu.models import Pizza

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity': item['quantity'],
            'override': True
        })
    address_form = AddressSelectForm(user=request.user)
    return render(request, 'cart/cart_detail.html', {'cart': cart, 'address_form': address_form})


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        product = get_object_or_404(Pizza, id=product_id)
        cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])
        return redirect('cart:detail')
    

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Pizza, id=product_id)
    cart.remove(product)
    return redirect('cart:detail')


@require_POST
def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect('cart:detail')

cart/templates/cart/cart_detail.html
{% extends 'base.html' %}

{% block title %}Cart{% endblock title %}

{% block content %}
    <h1>Your cart ({{ cart|length }})</h1>
    {% if cart|length == 0 %}
        <p>Cart is empty.</p>
    {% else %}
        <table>
            <tr>
                <th>Product</th>
                <th>Quantity</th>
                <th>Remove</th>
                <th>Unit price</th>
                <th>Price</th>
            </tr>
            {% for item in cart %}
            {% with item.product as product %}
                <tr>
                    <td>{{ product }}</td>
                    <td>
                        <form action="{% url 'cart:add' product.id %}" method="post">
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.override }}
                            <input type="submit" value="Update">
                            {% csrf_token %}
                        </form>
                    </td>
                    <td>
                        <form action="{% url 'cart:remove' product.id %}" method="post">
                            <input type="submit" value="Remove">
                            {% csrf_token %}
                        </form>
                    </td>
                    <td>${{ item.price }}</td>
                    <td>${{ item.total_price }}</td>
                </tr>
            {% endwith %}
            {% endfor %}
            <tr>
                <td>Total</td>
                <td colspan="3"></td>
                <td>${{ cart.get_total_price }}</td>
            </tr>
        </table>

        <div>
            <h3>Clear cart</h3>
            <form action="{% url 'cart:clear' %}" method="post">
                {% csrf_token %}
                <input type="submit" value="Clear">
            </form>
        </div>

        <form action="{% url 'menu:order' %}" method="post">
            {% csrf_token %}
            <div>
                <h2>Choose your address</h2>
                {{ address_form }}
            </div>
            <input type="submit" value="Create order">
        </form>
    {% endif %}
{% endblock content %}