cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='detail'),
    path('add/<int:product_id>/', views.cart_add, name='add'),
    path('remove/<int:product_id>/', views.cart_remove, name='remove'),
    path('clear/', views.cart_clear, name='clear'), 
]

controller/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', include('menu.urls', namespace="menu")),
    path('user/', include('user.urls', namespace="user")),
    path('cart/', include('cart.urls', namespace="cart")),
    path('', include('shop.urls', namespace="shop")),
]

if settings.DEBUG or settings.TESTING_MODE:
    import debug_toolbar
    urlpatterns += [url('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'

urlpatterns = [
    path('', views.index, name="index"),
    path('add/', views.add_to_cart, name="add"),
    path('order/', views.create_order, name="order"),
    path('order-created/', views.order_created, name="order_created"),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name="home")
]

user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'user'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name="register"),
    path('order/<int:id>/', views.order_detail, name="order"),
    path('', views.profile, name="profile"),
]

shop/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'shop/index.html')

shop/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
    {% include "header.html" %}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    {% include "footer.html" %}
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

shop/templates/footer.html
<footer>
    <p><a href="https://github.com/chromium7/django_pizza">Source Code</a></p>
</footer>

shop/templates/header.html
<nav>
    <ul>
        <li><a href="{% url 'shop:home' %}">Home</a></li>
        <li><a href="{% url 'menu:index' %}">Menu</a></li>
        {% if user.is_authenticated %}
            <li><a href="{% url 'cart:detail' %}">Cart ({{ cart|length }})</a></li>
            <li><a href="{% url 'user:profile' %}">{{ user.username }}</a></li>
            <li><a href="{% url 'user:logout' %}">Logout</a></li>
        {% else %}
            <li><a href="{% url 'user:login' %}">Login</a></li>
            <li><a href="{% url 'user:register' %}">Sign up</a></li>
        {% endif %}
    </ul>
</nav>